### ISSUE TITLE
Nms variable dtype mismatch

### ISSUE THREAD

**Issue by TFisichella** [choyingw/SynergyNet#15]
Hi,

I installed the project without issues, I just had to comment line 49 in FaceBoxes/utils/build.py for Cython to compile but when I run python.exe singleImage.py -f demo\0.png

I get this issue :

Process the image:  demo\0.png
Traceback (most recent call last):
  File "...\SynergyNet\singleImage.py", line 129, in <module>
    main(args)
  File "...\SynergyNet\singleImage.py", line 60, in main
    rects = face_boxes(img_ori)
  File "...\SynergyNet\FaceBoxes\FaceBoxes.py", line 120, in __call__
    keep = nms(dets, nms_threshold)
  File "...\SynergyNet\FaceBoxes\utils\nms_wrapper.py", line 18, in nms
    return cpu_nms(dets, thresh)
  File "nms\cpu_nms.pyx", line 25, in nms.cpu_nms.cpu_nms
ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'

Do you know by any chance, how I can fix this ?

Thank you very much

**Comment by Jiooum102** [comment]
@TFisichella I found a related issue [here](https://github.com/cleardusk/3DDFA_V2/issues/12#issuecomment-697479173). Hope it could help.
