### ISSUE TITLE
UnboundLocalError: local variable 'tri' referenced before assignment

### ISSUE THREAD

**Issue by zhanghm1995** [choyingw/SynergyNet#16]
Hello, thank your for sharing this amazing work.

When I run the `python singleImage.py -f img` command, I got the error that:
```
Process the image:  img/sample_1.jpg
Traceback (most recent call last):
  File "singleImage.py", line 129, in <module>
    main(args)
  File "singleImage.py", line 106, in main
    render(img_ori, vertices_lst, alpha=0.6, wfp=f'inference_output/rendering_overlay/{name}.jpg')
  File "~/SynergyNet/utils/render.py", line 42, in render
    overlap = render_app(ver, tri, overlap, texture=tex)
UnboundLocalError: local variable 'tri' referenced before assignment
```
I found that it is because the `connectivity` argument is None by default, but I don't know how to set it to a correct value.

**Comment by zhanghm1995** [comment]
I solved this problem.

**Comment by cuizhanyuan** [comment]
I got the same error that.Can you tell me how to solve this problem?@zhanghm1995
